# \u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E  \u53EF\u4FEE\u6539\u6307\u5B9A\u7684\u6570\u636E\u5E93
spring.datasource.url=jdbc:mysql://mysql.dstp-dev:3306/dstp_client
spring.datasource.username=dstp
spring.datasource.password=6i8899P9XCvnWk}AKC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \u8981\u751F\u6210\u76F8\u5173\u4EE3\u7801\u7684\u8868\u540D
generator.tables=doc_check_order,doc_check_order_invoice

# \u751F\u6210\u7684\u5B9E\u4F53\u5BF9\u8C61\u3001mapper\u3001repository \u8DEF\u5F84\u914D\u7F6E  dstp\u9879\u76EE\u4FEE\u6539\u4FEE\u6539example\u5373\u53EF
generator.entity-package=com.supplychain.dstp.test.model
generator.mapper-package=com.supplychain.dstp.test.mapper
generator.repository-package=com.supplychain.dstp.test.repository
# \u6587\u4EF6\u8DEF\u5F84\u914D\u7F6E
generator.entity-path=src/main/java
generator.mapper-path=src/main/java
generator.mapper-xml-path=src/main/resources/mapper
generator.repository-path=src/main/java

# XML\u6587\u4EF6\u5305\u8DEF\u5F84\u914D\u7F6E \u53EF\u66FF\u6362example
generator.mapper-xml-package=test